---
- name: Install Docker on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update apt repository and install dependencies
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      become: true

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present
      become: true

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes
      become: true

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
      become: true

    - name: Add user to Docker group
      user:
        name: vagrant
        group: docker
        append: yes
      become: true
