Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    
    config.vm.network "public_network", type: "dhcp", ip: "192.168.1.120"

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision.yml"  
    end

    # Sekcja provider dla VirtualBox
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "6144"  
        vb.cpus = 2       
        vb.name = "portfolio_project_ubuntu" 
    end
end
