services:
  sonar_db:
    image: postgres:15
    restart: unless-stopped
    environment:
    #oczywiście zmienić te dane na inne dla bezpieczenstwa
      POSTGRES_USER: sonar 
      POSTGRES_PASSWORD: sonar 
      POSTGRES_DB: sonar 
    volumes:
      - sonar_db:/var/lib/postgresql
    networks:
      - jenkins
  sonarqube:
    image: sonarqube:lts-community
    restart: unless-stopped
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_all:/opt/sonarqube
    networks:
      - jenkins
    depends_on:
      - sonar_db

volumes:
  sonarqube_all:
  sonar_db:

networks:
  jenkins:
    external: true