---
- name: Install Jenkins using Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Create directory for Jenkins Docker setup
      file:
        path: /docker/jenkins
        state: directory
    
    - name: Copy Dockerfile to the remote server with a new name
      copy:
        src: ./files/Dockerfile-jenkins
        dest: /docker/jenkins/Dockerfile

    - name: Copy docker-compose.yml to create Jenkins
      copy:
        src: ./files/docker-compose-jenkins.yml
        dest: /docker/jenkins/docker-compose.yml

    - name: Build Docker image from Dockerfile
      command: docker build -t myjenkins-blueocean .
      args:
        chdir: /docker/jenkins

    - name: Check if Jenkins network exists
      shell: docker network ls --filter name=jenkins -q
      register: network_exists
      changed_when: false

    - name: Create Jenkins external network in Docker if not exists
      command: docker network create jenkins
      when: network_exists.stdout == ""
        
    - name: Start Jenkins container using docker-compose
      command: docker compose up -d
      args:
        chdir: /docker/jenkins

    - name: Run ssh-keyscan inside the jenkins-blueocean container
      command: docker exec jenkins-blueocean sh -c "ssh-keyscan github.com >> ~/.ssh/known_hosts"
      args:
        chdir: /docker/jenkins
      
    - name: Create directory for sonarqube Docker setup
      file:
        path: /docker/sonarqube
        state: directory

    - name: Copy docker-compose.yml to create sonarqube
      copy:
        src: ./files/docker-compose-sonar.yml
        dest: /docker/sonarqube/docker-compose.yml

    - name: Start Sonarqbue container using docker-compose
      command: docker compose up -d
      args:
        chdir: /docker/sonarqube