name: Build and Create PR

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v4

      # Ustawienie Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Instalacja zależności
      - name: Install dependencies
        run: npm install

      # Budowanie projektu
      - name: Run build
        run: npm run build

#   create-pr:
#     needs: build
#     runs-on: ubuntu-latest
#     if: success()

#     steps:
#       # Checkout kodu
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Commit changes
#         run: |
#           git add .
#           git commit -m "Automatyczny commit po zbudowaniu"
#           git push origin dev

#       # Tworzenie Pull Requesta z `dev` do `main`
#       - name: Create Pull Request to main
#         uses: peter-evans/create-pull-request@v7
#         with:
#           branch: dev         # PR z `dev` do `main`
#           base: main          # Docelowy branch (chroniony)
#           commit-message: 'Automated build from dev'
#           title: 'Automated PR: Sync dev with main'
#           body: |
#             This pull request was automatically created after a successful build of the `dev` branch.
#             Please review and merge it.
#           labels: |
#             automated
#             ready-for-review
